### ISSUE TITLE
编译zlib为wasm失败

### ISSUE THREAD

**Issue by yunwen11** [xmake-io/xmake#4444]
### Xmake 版本

2.8.5

### 操作系统版本和架构

macOS M2 14.1

### 描述问题

编译wasm失败，显示emar的参数不对，但在zlib下emconfigure后编译可以成功。

### 期待的结果

可以编译通过。

### 工程配置

```
package("z")
    set_urls("https://www.zlib.net/zlib-$(version).tar.xz")
    add_versions("1.3", "8a9ba2898e1d0d774eca6ba5b4627a11e5588ba85c8851336eb38de4683050a7")
    on_install("wasm", function (package)
        import("package.tools.autoconf").install(package)
    end)
package_end()
```

### 附加信息和错误日志

错误信息：
```
yun@ mmcut$ xmake f -p wasm -y -vD
checking for architecture ... wasm32
checking for emsdk directory ... no
checking for emcc ... /opt/homebrew/bin/emcc
checking for unzip ... /usr/bin/unzip
checking for git ... /opt/homebrew/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
finding z from xmake ..
checking for xmake::z ... no
checking for ping ... /sbin/ping
pinging the host(www.zlib.net) ... 192 ms
/usr/bin/tar -xf zlib-1.3.tar.xz -C source.tmp
patching ~/Downloads/01-remove_libtool_for_Darwin.patch to z-1.3 ..
/opt/homebrew/bin/git apply --reject --ignore-whitespace /var/folders/33/5mr4jfzx6h9f45ks4vnq6zvm0000gn/T/.xmake501/231129/patches/z/1.3/01-remove_libtool_for_Darwin.patch
Checking patch configure...
Applied patch configure cleanly.
checking for emsdk directory ... no
checking for emcc ... /opt/homebrew/bin/emcc
checking for the c compiler (cc) ... emcc
checking for emsdk directory ... no
checking for /opt/homebrew/bin/emcc ... ok
checking for flags (-fPIC) ... ok
> emcc "-fPIC"
checking for emsdk directory ... no
checking for emcc ... /opt/homebrew/bin/emcc
checking for the assember (as) ... emcc
checking for emsdk directory ... no
checking for flags (-fPIC) ... no
> emcc "-fPIC"
checkinfo: @programdir/core/sandbox/modules/os.lua:273: clang++: warning: /var/folders/33/5mr4jfzx6h9f45ks4vnq6zvm0000gn/T/.xmake501/231129/_F3443E45635A466AA3BEAE9DE99B4339.s: 'assembler' input unused [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-fPIC' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-c' [-Wunused-command-line-argument]
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc.py", line 4549, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc.py", line 4542, in main
    ret = run(args)
          ^^^^^^^^^
  File "/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc.py", line 1320, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc.py", line 3170, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc.py", line 3164, in compile_source_file
    assert os.path.exists(output_file)
AssertionError

stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:923]:
    [@programdir/core/sandbox/modules/os.lua:273]: in function 'runv'
    [@programdir/modules/detect/tools/gcc/has_flags.lua:42]:
checking for emsdk directory ... no
checking for emcc ... /opt/homebrew/bin/emcc
checking for the c++ compiler (cxx) ... emcc
checking for emsdk directory ... no
checking for flags (-fPIC) ... ok
> emcc "-fPIC"
checking for emsdk directory ... no
checking for em++ ... /opt/homebrew/bin/em++
checking for the linker (ld) ... em++
checking for emsdk directory ... no
checking for /opt/homebrew/bin/em++ ... ok
checking for flags (-fPIC) ... ok
> em++ "-fPIC"
checking for emsdk directory ... no
checking for em++ ... /opt/homebrew/bin/em++
checking for the shared library linker (sh) ... em++
checking for emsdk directory ... no
checking for flags (-fPIC) ... ok
> em++ "-fPIC" "-shared"
checking for emsdk directory ... no
checking for emsdk directory ... no
checking for emar ... /opt/homebrew/bin/emar
checking for the static library archiver (ar) ... emar
checking for emranlib ... /opt/homebrew/bin/emranlib
checking for unknown toolkind ranlib (ranlib) ... emranlib
./configure --prefix=/Users/yun/.xmake/packages/z/z/1.3/c649c96aca6444c0b03d79e5a055fabe
Checking for shared library support...
Building shared library libz.so.1.3 with /opt/homebrew/bin/emcc.
Checking for size_t... Yes.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... Yes.
checking for make ... /usr/bin/make
/usr/bin/make -j10 V=1
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -c -o example.o test/example.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o adler32.o adler32.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o crc32.o crc32.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o deflate.o deflate.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o infback.o infback.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inffast.o inffast.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inflate.o inflate.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inftrees.o inftrees.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o trees.o trees.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o zutil.o zutil.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o compress.o compress.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o uncompr.o uncompr.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzclose.o gzclose.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzlib.o gzlib.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzread.o gzread.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzwrite.o gzwrite.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -c -o minigzip.o test/minigzip.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/adler32.o adler32.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/crc32.o crc32.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/deflate.o deflate.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/infback.o infback.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/inffast.o inffast.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/inflate.o inflate.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/inftrees.o inftrees.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/trees.o trees.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/zutil.o zutil.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/compress.o compress.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/uncompr.o uncompr.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/gzclose.o gzclose.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/gzlib.o gzlib.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/gzread.o gzread.c
/opt/homebrew/bin/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/gzwrite.o gzwrite.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -D_FILE_OFFSET_BITS=64 -c -o example64.o test/example.c
/opt/homebrew/bin/emcc -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -D_FILE_OFFSET_BITS=64 -c -o minigzip64.o test/minigzip.c
/opt/homebrew/bin/emar  libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/llvm/bin/llvm-ar: error: unknown option z
OVERVIEW: LLVM Archiver

USAGE: llvm-ar [options] [-]<operation>[modifiers] [relpos] [count] <archive> [files]
       llvm-ar -M [<mri-script]
```

在zlib目录下，直接`emconfigure ./configure`后再`emmake make`或`make`，都可以成功：
```
yun@ zlib-1.3$ emconfigure ./configure
configure: ./configure
Checking for shared library support...
Building shared library libz.so.1.3 with /opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc.
Checking for size_t... Yes.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... Yes.
yun@ zlib-1.3$ make
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -c -o example.o test/example.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o adler32.o adler32.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o crc32.o crc32.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o deflate.o deflate.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o infback.o infback.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inffast.o inffast.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inflate.o inflate.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inftrees.o inftrees.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o trees.o trees.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o zutil.o zutil.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o compress.o compress.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o uncompr.o uncompr.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzclose.o gzclose.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzlib.o gzlib.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzread.o gzread.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzwrite.o gzwrite.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o example example.o  -L. libz.a
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -c -o minigzip.o test/minigzip.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o minigzip minigzip.o  -L. libz.a
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/adler32.o adler32.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/crc32.o crc32.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/deflate.o deflate.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/infback.o infback.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/inffast.o inffast.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/inflate.o inflate.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/inftrees.o inftrees.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/trees.o trees.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/zutil.o zutil.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/compress.o compress.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/uncompr.o uncompr.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/gzclose.o gzclose.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/gzlib.o gzlib.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/gzread.o gzread.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/gzwrite.o gzwrite.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o libz.so.1.3 adler32.lo crc32.lo deflate.lo infback.lo inffast.lo inflate.lo inftrees.lo trees.lo zutil.lo compress.lo uncompr.lo gzclose.lo gzlib.lo gzread.lo gzwrite.lo  -lc
emcc: warning: object file output extension (.so) used for non-object output.  If you meant to build an object file please use `-c, `-r`, or `-shared` [-Wemcc]
rm -f libz.so libz.so.1
ln -s libz.so.1.3 libz.so
ln -s libz.so.1.3 libz.so.1
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o examplesh example.o  -L. libz.so.1.3
emcc: warning: unrecognized file type: `libz.so.1.3`.  Mapping to `-lz` and hoping for the best [-Wmap-unrecognized-libraries]
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o minigzipsh minigzip.o  -L. libz.so.1.3
emcc: warning: unrecognized file type: `libz.so.1.3`.  Mapping to `-lz` and hoping for the best [-Wmap-unrecognized-libraries]
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -D_FILE_OFFSET_BITS=64 -c -o example64.o test/example.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o example64 example64.o  -L. libz.a
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -D_FILE_OFFSET_BITS=64 -c -o minigzip64.o test/minigzip.c
/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o minigzip64 minigzip64.o  -L. libz.a
```

**Comment by yunwen11** [comment]
从日志上看，ar需要rc参数。在zlib目录下，执行ar的命令`/opt/homebrew/Cellar/emscripten/3.1.48/libexec/emar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o`若把rc参数去掉，会报一样的错误

**Comment by waruqi** [comment]
官方仓库包全平台支持，为啥不用呢？ https://github.com/xmake-io/xmake-repo/blob/dev/packages/z/zlib/xmake.lua

就是因为 zlib 的 configure 问题太多，我才用 xmake port 了。。自己都不用写包，直接 `add_requires("zlib")` 就好了

它这里 rc 没加，是 zlib 的 configure 的问题，检测部分配置不对，导致没加上 rc 而已。

**Comment by yunwen11** [comment]
开发团队你好，是这样，公司要求所有包我们需要从源码构建，我们也需要控制编译的各种选项，如果用仓库里的包，当前还不是一个可以被完全信任的行为，如果发生什么问题，我们无法自行解决，比如要打补丁什么的。

或者换一个角度，能否像cmake的ExternalProject_Add那样，可以让自定义configure、build、install等命令。

现在面临的问题是，在zlib编译wasm时，emconfigure configure + emmake make可以成功，但xmake我不知道可以如何完成相同的行为。如果有一个仓库没有收录的库，同样emconfigure configure + emmake make可以成功，我却无法用xmake尽量复用这个过程，这无疑增加了包编译的难度。

**Comment by waruqi** [comment]
> 开发团队你好，是这样，公司要求所有包我们需要从源码构建，我们也需要控制编译的各种选项，如果用仓库里的包，当前还不是一个可以被完全信任的行为，如果发生什么问题，我们无法自行解决，比如要打补丁什么的。

这好像也没啥冲突么，直接自己 clone 下 xmake-repo 到你们本地私有仓库，甚至直接在你们自己项目的自建仓库维护，不就好了么。。

可以自建仓库，也可以直接项目中维护仓库，也可以直接 copy package到 xmake.lua 直接维护。。反正切到你们自己的仓库，想怎么改，想怎么加补丁 都是你们的事情。。

但是为啥非要用zlib 原生 configure 呢，我都说了那个有问题，我们才 xmake.lua port 的。。。你直接 copy 过来 xmake-repo/zlib 的完全ok的 构建脚本，直接用么。。随便改。。又不是非得让你直接访问 xmake-repo 装包

**Comment by yunwen11** [comment]
zlib是一个已经收录了的库，对于其它没有收录的库呢？

**Comment by waruqi** [comment]
> zlib是一个已经收录了的库，对于其它没有收录的库呢？

没收录的，自己仓库写包配置啊

**Comment by waruqi** [comment]
> 所以问题就又回到了：一个未收录的库，如果emconfigure configure + emmake make可以成功，但是package.tools.autoconf不能成功（和zlib一样的情况），我则要像port zlib一样去处理，而不是复用emconfigure configure + emmake make的路径。

不是，仅仅 zlib 那个有问题。。xmake-repo 里面一堆用 configure 构建的库了，都支持 wasm 。。你可以自己去看看 

https://github.com/xmake-io/xmake-repo/blob/4008de50367abe3554f52460fc5f09a744073cec/packages/l/lcms/xmake.lua#L32

https://github.com/xmake-io/xmake-repo/blob/4008de50367abe3554f52460fc5f09a744073cec/packages/l/libiconv/xmake.lua#L51

目前其他包，调用 configure 支持 wasm ，从来没遇到过问题

如果你非要 zlib 那个 configure 也支持，你可以自己对 zlib 的 configure 打 patch 。。那是 zlib 的 configure 问题。。并不是 xmake 对 wasm configure 不支持

**Comment by yunwen11** [comment]
因为当前正在进行构建系统的选型，不是说不能用xmake port脚本，而是验证对于今后用到或可能用到的库，当没有现成脚本时，有兜底的开发成本较小的方法。（原则上公司要求尽量使用各库的官方源代码和构建工具）

我对zlib尝试使用其内置的cmake：
```lua
package("z")
    set_urls("https://www.zlib.net/zlib-$(version).tar.xz")
    add_versions("1.3", "8a9ba2898e1d0d774eca6ba5b4627a11e5588ba85c8851336eb38de4683050a7")
    on_install("wasm", function (package)
        import("package.tools.cmake").install(package, {})
    end)
package_end()
```

会报错：
```
checking for architecture ... wasm32
checking for emsdk directory ... no
checking for emcc ... /opt/homebrew/bin/emcc
checking for unzip ... /usr/bin/unzip
checking for git ... /opt/homebrew/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
finding z from xmake ..
checking for xmake::z ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
  -> z 1.3
please input: y (y/n/m)
y
checking for ping ... /sbin/ping
pinging the host(www.zlib.net) ... 264 ms
/usr/bin/tar -xf zlib-1.3.tar.xz -C source.tmp
patching /Users/yun/Large/Src/Mobvoi/mmcut/src/3rd/01-remove_libtool_for_Darwin.patch to z-1.3 ..
/opt/homebrew/bin/git apply --reject --ignore-whitespace /var/folders/33/5mr4jfzx6h9f45ks4vnq6zvm0000gn/T/.xmake501/231130/patches/z/1.3/01-remove_libtool_for_Darwin.patch
Checking patch configure...
Applied patch configure cleanly.
checking for emsdk directory ... no
error: @programdir/modules/package/tools/cmake.lua:484: emscripten not found!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:923]: in function 'raiselevel'
    [@programdir/core/sandbox/modules/utils.lua:149]: in function 'assert'
    [@programdir/modules/package/tools/cmake.lua:484]: in function '_get_configs_for_wasm'
    [@programdir/modules/package/tools/cmake.lua:718]: in function '_get_configs'
    [@programdir/modules/package/tools/cmake.lua:1014]: in function 'install'
    [./src/3rd/xmake.lua:10]: in function 'script'
    [...dir/modules/private/action/require/impl/utils/filter.lua:125]: in function 'call'
    [.../modules/private/action/require/impl/actions/install.lua:366]:

  => install z 1.3 .. failed
error: @programdir/core/main.lua:309: @programdir/modules/async/runjobs.lua:320: .../modules/private/action/require/impl/actions/install.lua:471: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:923]:
    [.../modules/private/action/require/impl/actions/install.lua:471]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:330]:
    [...modules/private/action/require/impl/install_packages.lua:479]: in function 'jobfunc'
    [@programdir/modules/async/runjobs.lua:237]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:923: in function 'os.raiselevel'
	(...tail calls...)
	@programdir/core/main.lua:309: in upvalue 'cotask'
	@programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>
```

这看起来是说无法找到emsdk？但我系统中是有装emsdk的：
```
$ emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.48-git
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by waruqi** [comment]
你调下 https://github.com/xmake-io/xmake/blob/master/xmake/modules/detect/sdks/find_emsdk.lua 确认下 $EMSDK 设置了没有

**Comment by yunwen11** [comment]
抱歉，我不太理解你的意思：
```shell
yun@ xmake$ lua ./modules/detect/sdks/find_emsdk.lua "/opt/homebrew/Cellar/emscripten/3.1.48"
lua: ./modules/detect/sdks/find_emsdk.lua:22: attempt to call a nil value (global 'import')
stack traceback:
	./modules/detect/sdks/find_emsdk.lua:22: in main chunk
	[C]: in ?
yun@ xmake$ lua ./modules/detect/sdks/find_emsdk.lua "/opt/homebrew/Cellar/emscripten/3.1.48" {}
lua: ./modules/detect/sdks/find_emsdk.lua:22: attempt to call a nil value (global 'import')
stack traceback:
	./modules/detect/sdks/find_emsdk.lua:22: in main chunk
	[C]: in ?
```

**Comment by yunwen11** [comment]
对，我用的是brew安装的。但是我很奇怪，为什么package.tools.autoconf不会遇到这个问题，检测逻辑不同吗？

我明天上班试一下。

**Comment by waruqi** [comment]
> 对，我用的是brew安装的。但是我很奇怪，为什么package.tools.autoconf不会遇到这个问题，检测逻辑不同吗？
> 
> 我明天上班试一下。

autoconf 那个只需要 xmake 透传 emcc toolchain 给 configure。 能找到 emcc emar 这些就行，而 cmake 那个不是直接透传的 emcc ，而是使用 emsdk 里面自带的 cmake toolchain 配置，所以要额外调用 find_emsdk 找到 emsdk 根目录，再去取对应的 cmake toolchain 。。https://github.com/xmake-io/xmake/blob/f37de48cc3c015c429453c2ffdfd0d527c58cc87/xmake/modules/package/tools/cmake.lua#L483

**Comment by yunwen11** [comment]
我改用官方的emsdk，现在cmake可以了。

**Comment by yunwen11** [comment]
OK，辛苦了，非常感谢！
